/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantPreviewRouteImport } from './routes/tenant-preview'
import { Route as RecoverySuccessRouteImport } from './routes/recovery-success'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AtRiskRouteImport } from './routes/at-risk'
import { Route as AddScheduleRouteImport } from './routes/add-schedule'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitIdRouteImport } from './routes/unit.$id'

const TenantPreviewRoute = TenantPreviewRouteImport.update({
  id: '/tenant-preview',
  path: '/tenant-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverySuccessRoute = RecoverySuccessRouteImport.update({
  id: '/recovery-success',
  path: '/recovery-success',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRiskRoute = AtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const AddScheduleRoute = AddScheduleRouteImport.update({
  id: '/add-schedule',
  path: '/add-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitIdRoute = UnitIdRouteImport.update({
  id: '/unit/$id',
  path: '/unit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-schedule': typeof AddScheduleRoute
  '/at-risk': typeof AtRiskRoute
  '/insights': typeof InsightsRoute
  '/recovery-success': typeof RecoverySuccessRoute
  '/tenant-preview': typeof TenantPreviewRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-schedule': typeof AddScheduleRoute
  '/at-risk': typeof AtRiskRoute
  '/insights': typeof InsightsRoute
  '/recovery-success': typeof RecoverySuccessRoute
  '/tenant-preview': typeof TenantPreviewRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-schedule': typeof AddScheduleRoute
  '/at-risk': typeof AtRiskRoute
  '/insights': typeof InsightsRoute
  '/recovery-success': typeof RecoverySuccessRoute
  '/tenant-preview': typeof TenantPreviewRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-schedule'
    | '/at-risk'
    | '/insights'
    | '/recovery-success'
    | '/tenant-preview'
    | '/unit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-schedule'
    | '/at-risk'
    | '/insights'
    | '/recovery-success'
    | '/tenant-preview'
    | '/unit/$id'
  id:
    | '__root__'
    | '/'
    | '/add-schedule'
    | '/at-risk'
    | '/insights'
    | '/recovery-success'
    | '/tenant-preview'
    | '/unit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddScheduleRoute: typeof AddScheduleRoute
  AtRiskRoute: typeof AtRiskRoute
  InsightsRoute: typeof InsightsRoute
  RecoverySuccessRoute: typeof RecoverySuccessRoute
  TenantPreviewRoute: typeof TenantPreviewRoute
  UnitIdRoute: typeof UnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant-preview': {
      id: '/tenant-preview'
      path: '/tenant-preview'
      fullPath: '/tenant-preview'
      preLoaderRoute: typeof TenantPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-success': {
      id: '/recovery-success'
      path: '/recovery-success'
      fullPath: '/recovery-success'
      preLoaderRoute: typeof RecoverySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-risk': {
      id: '/at-risk'
      path: '/at-risk'
      fullPath: '/at-risk'
      preLoaderRoute: typeof AtRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-schedule': {
      id: '/add-schedule'
      path: '/add-schedule'
      fullPath: '/add-schedule'
      preLoaderRoute: typeof AddScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$id': {
      id: '/unit/$id'
      path: '/unit/$id'
      fullPath: '/unit/$id'
      preLoaderRoute: typeof UnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddScheduleRoute: AddScheduleRoute,
  AtRiskRoute: AtRiskRoute,
  InsightsRoute: InsightsRoute,
  RecoverySuccessRoute: RecoverySuccessRoute,
  TenantPreviewRoute: TenantPreviewRoute,
  UnitIdRoute: UnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}